name: EconomyPlugin
main: edu.sjsu.cs185c.plugin.Plugin
version: 0.1.1

commands:
    money:
        description: Money operations
        usage: /money
    karma:
        description: Karma operations
        usage: /karma
    ach:
        description: Achievements operations
        usage: /ach
    prof:
        description: Profession operations
        usage: /prof <change/list> <new_prof>
    shop:
        description: Shopping operations
        usage: /shop <buy/sell/price> <item_name>